version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install

  build:
    commands:
      - npm test
      - echo "Building docker image."
      - pwd
      - docker build -t "docker-container-nodejs-lambda:latest" .
      - docker tag docker-container-nodejs-lambda:latest 598327188465.dkr.ecr.ap-southeast-2.amazonaws.com/docker-container-nodejs-lambda:latest
      - docker images
      - docker login -u AWS -p $(aws ecr get-login-password --region ap-southeast-2) 598327188465.dkr.ecr.ap-southeast-2.amazonaws.com
      - docker push 598327188465.dkr.ecr.ap-southeast-2.amazonaws.com/docker-container-nodejs-lambda:latest
      - echo "done"
