version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo "Building docker image"
      - pwd
      - ls
      - docker build --no-cache -t "docker-container-nodejs-lambda-2:latest" .
      - docker tag docker-container-nodejs-lambda:latest 598327188465.dkr.ecr.ap-southeast-2.amazonaws.com/docker-container-nodejs-lambda-2:latest
      - docker images
      - docker login -u AWS -p $(aws ecr get-login-password --region ap-southeast-2) 598327188465.dkr.ecr.ap-southeast-2.amazonaws.com
      - docker push 598327188465.dkr.ecr.ap-southeast-2.amazonaws.com/docker-container-nodejs-lambda-2:latest
      - aws lambda update-function-code --function-name docker-container-nodejs-lambda-2 --image-uri 598327188465.dkr.ecr.ap-southeast-2.amazonaws.com/docker-container-nodejs-lambda-2:latest
      - echo "done"
